
export const PATHS = {
  // Public auth
  SPLASH: "/",
  ROLE_SELECT: "/role-select",
  LOGIN: "/login",
  OTP: "/otp",
  COMING_SOON: "/coming-soon",

  // Onboarding Student
  CREATE_PROFILE: "/create-profile",
  ONBOARDING_SLIDES: "/onboarding",
  SUBJECT_SELECTION: "/subject-selection",
  LEARNING_PLAN: "/learning-plan",
  COUPON: "/coupon",
  PLAN_SCREEN: "/plan-screen",
  PAYMENT_FAILED: "/payment-failed",

  // Student tabs (StudentLayout)
  STUDENT_DASHBOARD: "/student-dashboard",
  ASK_DOUBT: "/ask-doubt",
  TEACHER_SEARCHING: "/teacher-searching",
  AI_CHAT: "/ai-chat",
  CHAT_SESSION: "/chat-session",
  LEADERBOARD: "/leaderboard",
  MCQ: "/mcq",
  LIVE_CLASSES: "/live-classes",
  PROFILE: "/profile",
  EDIT_PROFILE: "/profile/edit",
  WALLET: "/wallet",
  STUDENT_PROFILE_SETUP: "/student/profile/setup",
  STUDENT_NOTIFICATIONS: "/student-notifications",

  //Teacher Flow
  TEACHER_REGISTRATION:"/teacher-registration",
  QUALIFICATION_DETAILS:"/qualification-details",
  BASICPROFILE_DETAILS:"/basicprofile-details",
  EXPERIENCE_DETAILS:"/experience-details",
  TEACHER_SUBJECT_SELECTION:"/teacher-subject-selection",
  TEACHERCLASS_SELECTION:"/class-selection",
  BOARD_SELECTION:"/board-selection",
  LANGUAGE_SELECTION:"/language-selection",
  DOCUMENT_UPLOAD:"/document-upload",
  INTERVIEW_SCHEDULE:"/interview-schedule",
  TEACHER_DEMO_VIDEO:"/teacher-demo-video",
  PROFILE_REVIEW:"/profile-review",
  INTERVIEW_CONFIRMATION:"/interview-confirmation",
  VERIFICATION_STATUS:"/verification-status",
  TEACHER_DASHBOARD:"/teacher-dashboard",
  TEACHER_PROFILE:"/teacher-profile",
  TEACHER_REVIEWS: "/teacher-reviews",
  TEACHER_EDIT_PROFILE:"/teacher/edit-profile",
  REWARD_CENTER: "/teacher/reward-center",
  REFER_STUDENT: "/teacher/refer-student",
  REFER_TEACHER: "/teacher/refer-teacher",
  TEACHER_REFERRAL_HISTORY: "/teacher/referral-history",

    AVAILABILITY_STATUS: "/availability-status",
    DIRECT_REQUEST_NOTIFICATION: "/direct-request-notification",
    TEACHER_NOTIFICATIONS: "/teacher-notifications",
    TEACHER_WALLET: "/teacher-wallet",
    TEACHER_EARNINGS_HISTORY: "/teacher-earnings-history",
    TEACHER_SESSION_HISTORY: "/teacher-session-history",
    TEACHER_REQUESTS: "/teacher-requests",
    TEACHER_CLASSES: "/teacher-classes",
    CREATE_LIVE_CLASS: "/teacher-classes/create",
    TEACHER_LIBRARY: "/teacher-library",
    TEACHER_LIVE_SESSION: "/teacher-live-session",
    TEACHER_VIDEO_SESSION: "/teacher-video-session",
    TEACHER_AUDIO_SESSION: "/teacher-audio-session",
    TEACHER_CHAT_SESSION: "/teacher-chat-session",
    TEACHER_RESOLVE_DOUBT: "/teacher-resolve-doubt",

  // Student flows
  VIDEO_UPLOAD: "/video-upload",
  SHORT_VIDEO_FEED: "/short-video-feed",
  CREATOR_PROFILE: "/creator-profile/:id",
  DOUBT_SUBMITTED: "/doubt-submitted",
  AUDIO_CALL: "/audio-call",
  LIVE_SESSION: "/live-session",
  VIDEO_CALL_SESSION: "/video-call-session",
  SHORT_LIVE_SESSION: "/short-live-session",
  SESSION_FEEDBACK: "/session-feedback",
  SESSION_HISTORY: "/session-history",
  SPINNER: "/spinner",
  REFER_EARN: "/refer-earn",
  REFERRAL_HISTORY: "/referral-history",
  REFERRAL_REWARD: "/referral-reward",
  PLAN_UPGRADE: "/plan-upgrade",
  LIBRARY: "/library",
  USE_SUBSCRIPTION: "/use-subscription",
  USE_RECHARGE: "/use-recharge",


  //Parent Flow
  ADD_CHILD:"/add-child",
  PARENT_PENDING_APPROVAL: "/parent-pending-approval",
  PARENT_DASHBOARD:"/parent-dashboard",
  PARENT_LIVEACTIVITY:"/live-activity",
  PARENT_DOUBTHISTORY:"/doubt-history",
  PARENT_PROFILE: "/parent/profile",
  PARENT_ANALYTICS: "/parent/analytics",
  PARENT_TIME_ANALYTICS: "/parent/child/:studentId/usage",
  PARENT_CONTROLS: "/parent/controls",
  // Legacy
  DASHBOARD: "/dashboard",
} as const;

export type AppPath = (typeof PATHS)[keyof typeof PATHS];
